# numpy 문제 풀이

In [3]:
import numpy as np

# 문제1

In [54]:
# slicing 문제 : 다음의 데이터를 추철하는 하는 코드를 작성하시오.
datas = [[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]]

arr = np.array(datas)
arr
# ---------------------
# 출력 결과: 
# array([11, 45, 82])

array([[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]])

In [55]:
# 풀이
arr[:, -1]

array([11, 45, 82])

# 문제2

In [8]:
# numpy함수를 이용하여 10이하의 짝수와 홀수 각각의 리스트를 생성하고,
# 이 두가지 리스트를 사용하여 2차원의 데이터를 만들어라.
odd = np.arange(1, 10, 2)
even = np.arange(2, 11, 2)

# ---------------------
# # 출력 결과: 
# array([[ 1,  3,  5,  7,  9],
#        [ 2,  4,  6,  8, 10]])

In [57]:
# 풀이 
x = np.array([odd, even])
x

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

# 문제3

In [9]:
# 10부터 30까지 정수로 이루어진 1차원배열을 만든다음 2차원  (7, -1) 형태로 변환하시오.
# 그리고 최댓값과 최솟값을 구하시오.

# 출력결과 :
# [[10 11 12]
#  [13 14 15]
#  [16 17 18]
#  [19 20 21]
#  [22 23 24]
#  [25 26 27]
#  [28 29 30]]

max: 30
min: 10

In [52]:
x = np.arange(10,30+1)
x = x.reshape(7, -1)
print(f"max: {x.max()}")
print(f"max: {x.min()}")

max: 30
max: 10


# 문제4

In [75]:
# 문제: 아래 배열을 3행 4열 형태로 reshape 하시오. 변환된 배열에서 마지막 행만 출력하시오.
datas = [[10, 20, 30, 40, 50, 60],
         [70, 80, 90, 100, 110, 120]]


In [76]:
x = np.array(datas)
x.reshape(3,4)
x[-1]

array([ 70,  80,  90, 100, 110, 120])

# 문제5

In [45]:
# 코드와 그  출력값이 다음과 같을 때 0.6664104711248381을 출력하는 코드를 작성하시오.
import random
random.seed(12)
print(random.random())
print(random.random())
print(random.random())
# print(random.random())
# -----------------------
# 0.4745706786885481
# 0.6574725026572553
# 0.6664104711248381
# 0.14260035292536777

0.4745706786885481
0.6574725026572553
0.6664104711248381


# 문제6

In [37]:
# seed값을 5로 고정한 후 random.randint(1,11)을 세번 실행했을 때 나오는 값을 구하시오. 

In [42]:
import random
random.seed(5)
random.randint(1,11)

10

In [43]:
random.randint(1,11)

5

In [44]:
random.randint(1,11)

6

# 문제7

In [14]:
# (1) 1~25까지 step이 3개인 1차원의 배열을 만들고,
# (2) reshape을 이용하여 3x3행렬로 만드시오.
# ----------------------
# 출력결과
# (1)
# array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])
# (2) 
# array([[ 1,  4,  7],
#        [10, 13, 16],
#        [19, 22, 25]])

In [35]:
x = np.arange(1,25+1,3)
print(x)
x.reshape(-1,3)

[ 1  4  7 10 13 16 19 22 25]


array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

# 문제8

In [15]:
# arr의 각 행에서 최댓값만 추출하여 1차원 배열 형태로 출력하시오.
# ---------------------
import numpy as np

np.random.seed(11)
arr = np.random.random((4, 5))

# 문제9

In [17]:
# 다음을 출력하고 리스트 형태로 변환하여 출력하시오.
X = np.random.randint(1, 45, (3,4))
# ----------------
X.tolist()
# 결과값 예시: [[2, 27, 6, 41], [27, 23, 3, 3], [34, 30, 43, 25]]

[[1, 41, 28, 32], [6, 8, 36, 2], [4, 9, 24, 18]]

# 문제10

In [26]:
# reshape 함수를 사용해 1부터 30까지의 숫자 중 짝수를 찾아 (3,5)의 행렬로 만드시오.
# ------------------------------
# 출력 결과
# array([[ 2,  4,  6,  8, 10],
#        [12, 14, 16, 18, 20],
#        [22, 24, 26, 28, 30]])

In [27]:
# 문제 풀이
x = np.arange(0,30+1,2)
x = x[1:]
x.reshape(3,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

# 문제11

In [29]:
# reshape 함수를 사용해서 1부터 12까지 숫자를 배열 후 
# 1) 2차원으로 배열 한 후 
# 2) 다시 4행으로 정렬하시오
# ---------------------
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]]) 

In [62]:
arr = np.arange(1,12+1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
arr = arr.reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
# range을 이용하여 1~20까지 숫자를 나열한 후 4행 5형로 정렬하고 그 중 각 행의 최소값을 추출하시오
[int(arr[0].min()), int(arr[1].min()), int(arr[2].min()), int(arr[3].min())]


[1, 4, 7, 10]

In [73]:
# 각 행의 최소값, 열방향으로 인덱스롤 증가하면서 비교를 해야함.
arr.min(axis=1)

array([ 1,  4,  7, 10])